AllCops:
  NewCops: enable

  Exclude:
    - 'bin/*'
    - 'config/environment.rb'
    - 'config/environments/*'
    - 'config/initializers/*'
    - 'node_modules/**/*'
    - 'db/schema.rb'
    - 'config/environment.rb'